name: Deploy via SFTP (DEBUG MODE)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: poulin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true  # Se usi submodules, altrimenti rimuovilo

      - name: Debug completo (directory locali, FTP e variabili)
        run: |

          echo ""
          echo "🔍 **Step 1: Installazione e build del progetto**"
          npm install --prefix daily-milk/frontend
          npm run build --prefix daily-milk/frontend

          echo ""
          echo "🔍 **Step 3: Verifica directory build locale**"
          if [ -d "daily-milk/frontend/build" ] && [ "$(ls -A daily-milk/frontend/build)" ]; then
            echo "✅ La cartella daily-milk/frontend/build esiste ed è popolata."
          else
            echo "❌ ERRORE: La cartella daily-milk/frontend/build NON esiste o è vuota!"
            exit 1
          fi

          echo ""
          echo "🔍 **Step 7: Test connessione FTP**"
          if sshpass -p "${{ secrets.FTP_PASSWORD }}" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
            "${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_HOST }}" "echo '✅ Connessione FTP riuscita'"; then
            echo "✅ Connessione stabilita con successo."
          else
            echo "❌ ERRORE: Impossibile connettersi al server FTP!"
            exit 1
          fi

          echo ""
          echo "🔍 **Step 8: Controllo contenuto della cartella remota /ai/**"
          sshpass -p "${{ secrets.FTP_PASSWORD }}" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
            "${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_HOST }}" "ls -la /ai/" || echo "⚠️ Errore nel visualizzare il contenuto di /ai"

          echo ""
          echo "🔍 **Step 9: Controllo file myftp.txt su FTP con grep**"
          if sshpass -p "${{ secrets.FTP_PASSWORD }}" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
            "${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_HOST }}" "ls -la /ai/ | grep myftp.txt"; then
            echo "✅ File myftp.txt trovato su FTP. Procedo con l'upload."
          else
            echo "❌ File myftp.txt NON trovato su FTP. Procedo comunque con il deploy per debug."
          fi

      - name: Upload files via SFTP
        run: |
          echo ""
          echo "🚀 **Step 10: Upload dei file su SFTP**"
          sshpass -p "${{ secrets.FTP_PASSWORD }}" sftp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
            "${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_HOST }}" <<EOF
            put -r daily-milk/frontend/build/* /ai/
          EOF
          echo "✅ Upload completato."
        env:
          SSHPASS: ${{ secrets.FTP_PASSWORD }}
