name: Deploy via SFTP

on:
  workflow_dispatch: # Permette l'avvio manuale da GitHub Actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: ./dairy-milk/frontend

      - name: Build project
        run: |
          npm run build
        working-directory: ./dairy-milk/frontend

      - name: Debug build path
        run: ls -R dairy-milk/frontend/

      - name: Check build output
        run: ls -la ./dairy-milk/frontend

      - name: Verify if `myftp.txt` exists on FTP
        run: |
          if sshpass -p "${{ secrets.FTP_PASSWORD }}" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_HOST }} "test -f /ai/myftp.txt"; then
            echo "✅ File myftp.txt found on FTP. Proceeding with deployment."
          else
            echo "❌ File myftp.txt NOT found on FTP. Skipping deployment."
            exit 1
          fi
        env:
          SSHPASS: ${{ secrets.FTP_PASSWORD }}

      - name: Upload files via SFTP
        if: success()
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: "dairy-milk/frontend/build/*"
          target: "/ai"
          strip_components: 3
          script: |
            StrictHostKeyChecking=no
            UserKnownHostsFile=/dev/null
