name: Deploy via SFTP (DEBUG MODE)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: poulin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true  # Se usi submodules, altrimenti rimuovilo

      - name: Debug completo (directory locali, FTP e variabili)
        run: |

          echo ""
          echo "🔍 **Step 1: Installazione e build del progetto**"
          npm install --prefix daily-milk/frontend
          npm run build --prefix daily-milk/frontend

          echo ""
          echo "🔍 **Step 3: Verifica directory build locale**"
          if [ -d "daily-milk/frontend/build" ] && [ "$(ls -A daily-milk/frontend/build)" ]; then
            echo "✅ La cartella daily-milk/frontend/build esiste ed è popolata."
          else
            echo "❌ ERRORE: La cartella daily-milk/frontend/build NON esiste o è vuota!"
            exit 1
          fi

          echo ""
          echo "🔍 **Step 7: Test connessione SFTP**"
          sshpass -p "${{ secrets.FTP_PASSWORD }}" sftp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
            "${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_HOST }}" <<EOF
            ls /
          EOF
          if [ $? -eq 0 ]; then
            echo "✅ Connessione SFTP riuscita."
          else
            echo "❌ ERRORE: Impossibile connettersi al server SFTP!"
            exit 1
          fi

          echo ""
          echo "🔍 **Step 8: Controllo contenuto della cartella remota /ai/**"
          sshpass -p "${{ secrets.FTP_PASSWORD }}" sftp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
            "${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_HOST }}" <<EOF
            ls /ai
          EOF

          echo ""
          echo "🔍 **Step 9: Controllo file myftp.txt su SFTP**"
          sshpass -p "${{ secrets.FTP_PASSWORD }}" sftp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
            "${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_HOST }}" <<EOF
            ls /ai/myftp.txt
          EOF
          if [ $? -eq 0 ]; then
            echo "✅ File myftp.txt trovato su SFTP. Procedo con l'upload."
          else
            echo "❌ File myftp.txt NON trovato su SFTP. Procedo comunque con il deploy per debug."
          fi
        env:
          SSHPASS: ${{ secrets.FTP_PASSWORD }}
