name: Deploy via SFTP (DEBUG MODE)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true  # Se usi submodules, altrimenti rimuovilo

      - name: Debug completo (directory locali, FTP e variabili)
        run: |
          echo "🔍 **Step 1: Verifica struttura repository**"
          pwd
          ls -R || echo "⚠️ La cartella non esiste ancora"

          echo ""
          echo "🔍 **Step 2: URL di origine e destinazione**"
          echo "📂 Origine (local): daily-milk/frontend/build/"
          echo "📂 Destinazione (remote FTP): /ai"

          echo ""
          echo "🔍 **Step 3: Installazione e build del progetto**"
          npm install --prefix daily-milk/frontend
          npm run build --prefix daily-milk/frontend

          echo ""
          echo "🔍 **Step 4: Verifica directory build locale**"
          if [ -d "daily-milk/frontend/build" ] && [ "$(ls -A daily-milk/frontend/build)" ]; then
            echo "✅ La cartella daily-milk/frontend/build esiste ed è popolata."
          else
            echo "❌ ERRORE: La cartella daily-milk/frontend/build NON esiste o è vuota!"
            exit 1
          fi

          echo ""
          echo "📂 **Step 5: Contenuto della directory locale (daily-milk/frontend/build/)**"
          ls -R daily-milk/frontend/build/

          echo ""
          echo "🔍 **Step 6: Debug variabili FTP (senza password)**"
          echo "FTP Host: '${{ secrets.FTP_HOST }}'"
          echo "FTP Username: '${{ secrets.FTP_USERNAME }}'"
          echo "FTP Port: '22'"

          echo ""
          echo "🔍 **Step 7: Controllo contenuto della cartella remota /ai/**"
          sshpass -p "${{ secrets.FTP_PASSWORD }}" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
            "${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_HOST }}" "ls -la /ai" || echo "⚠️ Errore nel connettersi all'FTP"

          echo ""
          echo "🔍 **Step 8: Controllo file myftp.txt su FTP**"
          if sshpass -p "${{ secrets.FTP_PASSWORD }}" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
            "${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_HOST }}" "ls /ai/myftp.txt"; then
            echo "✅ File myftp.txt trovato su FTP. Procedo con l'upload."
          else
            echo "❌ File myftp.txt NON trovato su FTP. Blocchiamo il deploy per sicurezza."
            exit 1
          fi
        env:
          SSHPASS: ${{ secrets.FTP_PASSWORD }}

      - name: ❌ Upload files via SFTP (DISATTIVATO)
        if: false  # Disattiva l'upload per ora
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: "daily-milk/frontend/build/*"
          target: "/ai"
          strip_components: 3
          script: |
            StrictHostKeyChecking=no
            UserKnownHostsFile=/dev/null
