name: Deploy via SFTP

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Debug repository structure (verifica contenuto repo)
        run: ls -R

      - name: Print current directory
        run: pwd

      - name: Verifica se `dairy-milk/frontend` esiste
        run: |
          if [ -d "dairy-milk/frontend" ]; then
            echo "✅ La cartella dairy-milk/frontend esiste."
          else
            echo "❌ ERRORE: La cartella dairy-milk/frontend NON esiste!"
            exit 1
          fi

      - name: Install dependencies
        run: npm install
        working-directory: dairy-milk/frontend

      - name: Build project
        run: npm run build
        working-directory: dairy-milk/frontend

      - name: Debug build path
        run: ls -R dairy-milk/frontend/

      - name: Check build output
        run: ls -la dairy-milk/frontend/

      - name: Debug FTP credentials
        run: |
          echo "FTP Username: '${{ secrets.FTP_USERNAME }}'"
          echo "FTP Host: '${{ secrets.FTP_HOST }}'"

      - name: List files in FTP directory
        run: |
          sshpass -p "${{ secrets.FTP_PASSWORD }}" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
            "${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_HOST }}" "ls -la /ai"

      - name: Verify if `myftp.txt` exists on FTP
        run: |
          if sshpass -p "${{ secrets.FTP_PASSWORD }}" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
            "${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_HOST }}" "ls /ai/myftp.txt"; then
            echo "✅ File myftp.txt found on FTP. Proceeding with deployment."
          else
            echo "❌ File myftp.txt NOT found on FTP. Skipping deployment."
            exit 1
          fi
        env:
          SSHPASS: ${{ secrets.FTP_PASSWORD }}

      - name: Upload files via SFTP
        if: success()
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: "dairy-milk/frontend/build/*"
          target: "/ai"
          strip_components: 3
          script: |
            StrictHostKeyChecking=no
            UserKnownHostsFile=/dev/null
