name: Deploy via SFTP

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true  # Se usi submodules, altrimenti rimuovilo

      - name: Debug repository structure (verifica dopo il checkout)
        run: ls -R

      - name: Print current directory
        run: pwd

      - name: Verifica se `dairy-milk/frontend` esiste
        run: |
          if [ -d "dairy-milk/frontend" ]; then
            echo "✅ La cartella dairy-milk/frontend esiste."
          else
            echo "❌ ERRORE: La cartella dairy-milk/frontend NON esiste!"
            exit 1
          fi

      - name: Install dependencies
        run: npm install
        working-directory: dairy-milk/frontend

      - name: Build project
        run: npm run build
        working-directory: dairy-milk/frontend
